"""empty message

Revision ID: 19fe94b6db5b
Revises: 
Create Date: 2020-10-03 01:56:42.286185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fe94b6db5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=80), nullable=True),
    sa.Column('preco', sa.String(), nullable=True),
    sa.Column('data_venc', sa.Date(), nullable=True),
    sa.Column('comment', sa.Text(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=80), nullable=True),
    sa.Column('preco', sa.String(), nullable=True),
    sa.Column('data_venc', sa.Date(), nullable=True),
    sa.Column('comment', sa.Text(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_contas')
    op.drop_table('contas')
    # ### end Alembic commands ###
