"""empty message

Revision ID: 23d34429e96a
Revises: c9d4f7b6a603
Create Date: 2020-10-04 23:40:10.419351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d34429e96a'
down_revision = 'c9d4f7b6a603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historico_contas', sa.Column('pago', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historico_contas', 'pago')
    # ### end Alembic commands ###
