"""empty message

Revision ID: 33426da04897
Revises: 
Create Date: 2020-09-23 17:57:46.605278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33426da04897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=80), nullable=True),
    sa.Column('preco', sa.Float(precision=2), nullable=True),
    sa.Column('data_venc', sa.String(length=8), nullable=True),
    sa.Column('comment', sa.Text(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_contas')
    # ### end Alembic commands ###
