"""empty message

Revision ID: 65287024a633
Revises: 
Create Date: 2020-05-18 16:05:21.605337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65287024a633'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('preco', sa.Float(precision=2), nullable=True),
    sa.Column('data_venc', sa.String(length=6), nullable=True),
    sa.Column('comment', sa.Text(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contas')
    # ### end Alembic commands ###
