"""empty message

Revision ID: c9d4f7b6a603
Revises: 19fe94b6db5b
Create Date: 2020-10-04 23:38:55.113596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d4f7b6a603'
down_revision = '19fe94b6db5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas', sa.Column('pago', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas', 'pago')
    # ### end Alembic commands ###
