"""empty message

Revision ID: f0d0780f4d05
Revises: 
Create Date: 2020-06-19 14:32:50.584682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d0780f4d05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=80), nullable=True),
    sa.Column('preco', sa.Float(precision=2), nullable=True),
    sa.Column('data_venc', sa.Date(), nullable=True),
    sa.Column('comment', sa.Text(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contas')
    # ### end Alembic commands ###
